M48
; DRILL file {KiCad 7.0.0-da2b9df05c~163~ubuntu22.04.1} date Sun 19 Feb 2023 04:44:03 AM MSK
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T04:44:03+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~163~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X-0.43Y-0.0069
X-0.22Y-0.37
X0.22Y-0.37
X0.43Y-0.005
T0
M30
